[workspace]

members = [
  "myev",
  "myev-installer"
]

# [package.metadata.scripts]
# devbuild = "cargo build --release && cp ./target/release/myev . && sudo myev"
# devrun = "cargo build --release && sudo ./target/release/myev"
